import { DateExt, Game } from "./util";

// Yes, my friend, there is no DB. Everything is static.
const _GAMES: Game[] = [
	{
		gameTitle: "Bonus #1",
		songTitle: "Fasateen",
		songId: "ZGcOA27MEeU",
		songBPM: 118,
		artist: "Mashrou’ Leila",
		language: "Arabic",
		country: "LBN",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #2",
		songTitle: "Joromi",
		songId: "rbe7UefYCN8",
		songBPM: 106,
		artist: "Victor Uwaifo",
		language: "Igbo",
		country: "NGA",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #3",
		songTitle: "Chachachá",
		songId: "sDMxQF18yvA",
		songBPM: 111,
		artist: "Jósean Log",
		language: "Spanish",
		country: "MEX",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #4",
		songTitle: "ERE",
		songId: "Ohf3czrhCSY",
		songBPM: 111,
		artist: "juan karlos",
		language: "Tagalog",
		country: "PHL",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #4",
		songTitle: "-140",
		songId: "Y7CUHJ009do",
		songBPM: 171,
		artist: "Zemfira",
		language: "Russian",
		country: "RUS",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Daily #1 - 04 Aug 2024",
		songTitle: "Hafenwind",
		songId: "45hA4R2sDlo",
		songBPM: 146,
		artist: "Erotik Toy Records",
		language: "German",
		country: "DEU",
		date: "04 Aug 2024",
	},
	{
		gameTitle: "Daily #2 - 05 Aug 2024",
		songTitle: "Така як ти",
		songId: "ii5YNU0Q5ak",
		songBPM: 55,
		artist: "Океан Ельзи",
		language: "Ukrainian",
		country: "UKR",
		date: "05 Aug 2024",
	},
	// TODO
	{
		gameTitle: "Daily #3 - 06 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "06 Aug 2024",
	},
	{
		gameTitle: "Daily #4 - 07 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "07 Aug 2024",
	},
	{
		gameTitle: "Daily #5 - 08 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "08 Aug 2024",
	},
	{
		gameTitle: "Daily #6 - 09 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "09 Aug 2024",
	},
	{
		gameTitle: "Daily #7 - 10 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "10 Aug 2024",
	},
	{
		gameTitle: "Daily #8 - 11 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "11 Aug 2024",
	},
	{
		gameTitle: "Daily #9 - 12 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "12 Aug 2024",
	},
	{
		gameTitle: "Daily #10 - 13 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "13 Aug 2024",
	},
	{
		gameTitle: "Daily #11 - 14 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "14 Aug 2024",
	},
	{
		gameTitle: "Daily #12 - 15 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "15 Aug 2024",
	},
	{
		gameTitle: "Daily #13 - 16 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "16 Aug 2024",
	},
	{
		gameTitle: "Daily #14 - 17 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "17 Aug 2024",
	},
	{
		gameTitle: "Daily #15 - 18 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "18 Aug 2024",
	},
	{
		gameTitle: "Daily #16 - 19 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "19 Aug 2024",
	},
	{
		gameTitle: "Daily #17 - 20 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "20 Aug 2024",
	},
	{
		gameTitle: "Daily #18 - 21 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "21 Aug 2024",
	},
	{
		gameTitle: "Daily #19 - 22 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "22 Aug 2024",
	},
	{
		gameTitle: "Daily #20 - 23 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "23 Aug 2024",
	},
	{
		gameTitle: "Daily #21 - 24 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "24 Aug 2024",
	},
	{
		gameTitle: "Daily #22 - 25 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "25 Aug 2024",
	},
];

export const GAMES = _GAMES.filter((g) => {
	const today = new DateExt(undefined, true);
	const gameDate = new DateExt(g.date, true);
	return today.isAtOrAfter(gameDate);
});
