import { Game } from "./util";

// Yes, my friend, there is no DB. Everything is static.
export const GAMES: Record<string, Game> = {
	B1: {
		gameTitle: "Bonus #1",
		songTitle: "Fasateen",
		songId: "ZGcOA27MEeU",
		songBPM: 118,
		artist: "Mashrou’ Leila",
		country: "LBN",
		date: "03 Aug 2024",
	},
	B2: {
		gameTitle: "Bonus #2",
		songTitle: "Joromi",
		songId: "rbe7UefYCN8",
		songBPM: 106,
		artist: "Victor Uwaifo",
		country: "NGA",
		date: "03 Aug 2024",
	},
	B3: {
		gameTitle: "Bonus #3",
		songTitle: "Chachachá",
		songId: "sDMxQF18yvA",
		songBPM: 111,
		artist: "Jósean Log",
		country: "MEX",
		date: "03 Aug 2024",
	},
	B4: {
		gameTitle: "Bonus #4",
		songTitle: "ERE",
		songId: "Ohf3czrhCSY",
		songBPM: 111,
		artist: "juan karlos",
		country: "PHL",
		date: "03 Aug 2024",
	},
	B5: {
		gameTitle: "Bonus #4",
		songTitle: "-140",
		songId: "Y7CUHJ009do",
		songBPM: 171,
		artist: "Zemfira",
		country: "RUS",
		date: "03 Aug 2024",
	},
	"04 Aug 2024": {
		gameTitle: "Daily #1 - 04 Aug 2024",
		songTitle: "Hafenwind",
		songId: "45hA4R2sDlo",
		songBPM: 146,
		artist: "Erotik Toy Records",
		country: "DEU",
		date: "04 Aug 2024",
	},
	// "05 Aug 2024": {
	// 	gameTitle: "Daily #2 - 05 Aug 2024",
	// 	songTitle: "Така як ти",
	// 	songId: "ii5YNU0Q5ak",
	// 	songBPM: 55,
	// 	artist: "Океан Ельзи",
	// 	country: "UKR",
	// 	date: "05 Aug 2024",
	// },
};
