import { DateExt, Game } from "./util";

// Yes, my friend, there is no DB. Everything is static.
const _GAMES: Game[] = [
	{
		gameTitle: "Bonus #1",
		songTitle: "Fasateen",
		songId: "ZGcOA27MEeU",
		songBPM: 118,
		artist: "Mashrou’ Leila",
		language: "Arabic",
		country: "LBN",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #2",
		songTitle: "Joromi",
		songId: "rbe7UefYCN8",
		songBPM: 106,
		artist: "Victor Uwaifo",
		language: "Igbo",
		country: "NGA",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #3",
		songTitle: "Chachachá",
		songId: "sDMxQF18yvA",
		songBPM: 111,
		artist: "Jósean Log",
		language: "Spanish",
		country: "MEX",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #4",
		songTitle: "ERE",
		songId: "Ohf3czrhCSY",
		songBPM: 111,
		artist: "juan karlos",
		language: "Tagalog",
		country: "PHL",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Bonus #5",
		songTitle: "-140",
		songId: "Y7CUHJ009do",
		songBPM: 171,
		artist: "Zemfira",
		language: "Russian",
		country: "RUS",
		date: "03 Aug 2024",
	},
	{
		gameTitle: "Daily #1 - 04 Aug 2024",
		songTitle: "Hafenwind",
		songId: "45hA4R2sDlo",
		songBPM: 146,
		artist: "Erotik Toy Records",
		language: "German",
		country: "DEU",
		date: "04 Aug 2024",
	},
	{
		gameTitle: "Daily #2 - 05 Aug 2024",
		songTitle: "Така як ти",
		songId: "ii5YNU0Q5ak",
		songBPM: 55,
		artist: "Океан Ельзи",
		language: "Ukrainian",
		country: "UKR",
		date: "05 Aug 2024",
	},
	{
		gameTitle: "Daily #3 - 06 Aug 2024",
		songTitle: "Razna",
		songId: "g4JPsYTS5ns",
		songBPM: 125,
		artist: "Emaa",
		language: "Romanian",
		country: "ROU",
		date: "06 Aug 2024",
	},
	{
		gameTitle: "Daily #4 - 07 Aug 2024",
		songTitle: "Fagurt er í fjörðum",
		songId: "c_YvIun3xwI",
		songBPM: 56,
		artist: "Björk ",
		language: "Icelandic",
		country: "ISL",
		date: "07 Aug 2024",
	},
	{
		gameTitle: "Daily #5 - 08 Aug 2024",
		songTitle: "თბილისი რუკაზე (Tbilisi Rukaze)",
		songId: "xbOOp5zcZEA",
		songBPM: 120,
		artist: "არა",
		language: "Georgian",
		country: "GEO",
		date: "08 Aug 2024",
	},
	{
		gameTitle: "Daily #6 - 09 Aug 2024",
		songTitle: "Preciosa",
		songId: "o74m1qggLHo",
		songBPM: 114,
		artist: "Marc Anthony",
		language: "Spanish",
		country: "PRI",
		date: "09 Aug 2024",
	},
	{
		gameTitle: "Daily #7 - 10 Aug 2024",
		songTitle: "Stay With Me",
		songId: "moR4uw-NWLY",
		songBPM: 108,
		artist: "Miki Matsubara",
		language: "Japanese",
		country: "JPN",
		date: "10 Aug 2024",
	},
	{
		gameTitle: "Daily #8 - 11 Aug 2024",
		songTitle: "Melodia Ulotna",
		songId: "wO_lA6hV1Ag",
		songBPM: 0,
		artist: "Mela Koteluk",
		language: "Polish",
		country: "POL",
		date: "11 Aug 2024",
	},
	{
		gameTitle: "Daily #9 - 12 Aug 2024",
		songTitle: "La Flaca",
		songId: "r2g0pM3PMNQ",
		songBPM: 103,
		artist: "Jarabe De Palo",
		language: "Spanish",
		country: "ESP",
		date: "12 Aug 2024",
	},
	{
		gameTitle: "Daily #10 - 13 Aug 2024",
		songTitle: "Ievan Polkka",
		songId: "nbAHzYQIf40",
		songBPM: 118,
		artist: "Loituma",
		language: "Finnish",
		country: "FIN",
		date: "13 Aug 2024",
	},
	{
		gameTitle: "Daily #11 - 14 Aug 2024",
		songTitle: "Tennis Court",
		songId: "D8Ymd-OCucs",
		songBPM: 90,
		artist: "Lorde",
		language: "English",
		country: "NZL",
		date: "14 Aug 2024",
	},
	{
		gameTitle: "Daily #12 - 15 Aug 2024",
		songTitle: "Resham",
		songId: "BpeFXed4K6I",
		songBPM: 156,
		artist: "Nepathya",
		language: "Nepali",
		country: "NPL",
		date: "15 Aug 2024",
	},
	{
		gameTitle: "Daily #13 - 16 Aug 2024",
		songTitle: "Lys Og Varme",
		songId: "DNCCdfSUQ3I",
		songBPM: 114,
		artist: "Åge Alexandersen",
		language: "Norwegian",
		country: "NOR",
		date: "16 Aug 2024",
	},
	{
		gameTitle: "Daily #14 - 17 Aug 2024",
		songTitle: "Mafi Mennik",
		songId: "zNabqPd_qNQ",
		songBPM: 111,
		artist: "Aziz Maraka",
		language: "Arabic",
		country: "JOR",
		date: "17 Aug 2024",
	},
	{
		gameTitle: "Daily #15 - 18 Aug 2024",
		songTitle: "Sit Die Ligte Aan",
		songId: "YhVE2OHgHts",
		songBPM: 130,
		artist: "Steve Hofmeyr",
		language: "Afrikaans",
		country: "ZAF",
		date: "18 Aug 2024",
	},
	{
		gameTitle: "Daily #16 - 19 Aug 2024",
		songTitle: "Ela Partiu",
		songId: "syqJAgTQdlU",
		songBPM: 80,
		artist: "Tim Maia",
		language: "Portuguese",
		country: "BRA",
		date: "19 Aug 2024",
	},
	{
		gameTitle: "Daily #17 - 20 Aug 2024",
		songTitle: "Senandung Maaf",
		songId: "WJ9wTSjHnMY",
		songBPM: 120,
		artist: "White Shoes & The Couples Company",
		language: "Indonesian",
		country: "IDN",
		date: "20 Aug 2024",
	},
	{
		gameTitle: "Daily #18 - 21 Aug 2024",
		songTitle: "Polepšovna",
		songId: "mCN2uTQQw7w",
		songBPM: 120,
		artist: "Anna Vaverková",
		language: "Czech",
		country: "CZE",
		date: "21 Aug 2024",
	},
	{
		gameTitle: "Daily #19 - 22 Aug 2024",
		songTitle: "Гитарам",
		songId: "BLx1cDYncYg",
		songBPM: 125,
		artist: "Adil",
		language: "Kazakh",
		country: "KAZ",
		date: "22 Aug 2024",
	},
	{
		gameTitle: "Daily #20 - 23 Aug 2024",
		songTitle: "좋겠어 (I wish)",
		songId: "fmAIaHd7v6E",
		songBPM: 132,
		artist: "FTISLAND ",
		language: "Korean",
		country: "KOR",
		date: "23 Aug 2024",
	},
	{
		gameTitle: "Daily #21 - 24 Aug 2024",
		songTitle: "Chinggis Khaan",
		songId: "tcd59zMIadk",
		songBPM: 153,
		artist: "Khusugtun",
		language: "Mongolian",
		country: "MNG",
		date: "24 Aug 2024",
	},
	{
		gameTitle: "Daily #22 - 25 Aug 2024",
		songTitle: "أحبيني (Ahebini)",
		songId: "kEpOv49P6Yg",
		songBPM: 89,
		artist: "Kadim Al Saher",
		language: "Arabic",
		country: "IRQ",
		date: "25 Aug 2024",
	},
	{
		gameTitle: "Daily #23 - 26 Aug 2024",
		songTitle: "Belki Üstümüzden Bir Kuş Geçer",
		songId: "72nGwgu3JDg",
		songBPM: 100,
		artist: "Yüksek Sadakat",
		language: "Turkish",
		country: "TUR",
		date: "26 Aug 2024",
	},
	{
		gameTitle: "Daily #24 - 27 Aug 2024",
		songTitle: "ม.ให้อะไร",
		songId: "QrFX1s06aEU",
		songBPM: 144,
		artist: "Pongsit Kamphee",
		language: "Thai",
		country: "THA",
		date: "27 Aug 2024",
	},
	{
		gameTitle: "Daily #25 - 28 Aug 2024",
		songTitle: "Don't Blame It On Me",
		songId: "1Er9j7EAR2s",
		songBPM: 105,
		artist: "Michael Bublé",
		language: "English",
		country: "CAN",
		date: "28 Aug 2024",
	},
	{
		gameTitle: "Daily #26 - 29 Aug 2024",
		songTitle: "Maria Alucase",
		songId: "MNgA6G6V4YA",
		songBPM: 140,
		artist: "Carlos Burity",
		language: "Portuguese",
		country: "AGO",
		date: "29 Aug 2024",
	},
	{
		gameTitle: "Daily #27 - 30 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "30 Aug 2024",
	},
	{
		gameTitle: "Daily #28 - 31 Aug 2024",
		songTitle: "",
		songId: "",
		songBPM: 0,
		artist: "",
		language: "",
		country: "",
		date: "31 Aug 2024",
	},
];

export const GAMES = _GAMES.filter((g) => {
	const today = new DateExt(undefined, true);
	const gameDate = new DateExt(g.date, true);
	return today.isAtOrAfter(gameDate);
});
